#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DP-2 --primary --mode 1920x1080 --pos 0x0 --output VGA-1 --mode 1920x1080 --pos 1920x0 --output LVDS-1 --off
bspc monitor LVDS-1 -d I II III IV V VI VII VIII IX X 2>/dev/null
bspc monitor DP-2 -d I II III IV V 2>/dev/null
bspc monitor VGA-1 -d VI VII VIII IX X
#bspc rule -a '*' monitor='VGA-1' state=fullscreen
bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config normal_border_color '#1f1f1f'
bspc config focused_border_color '#30302f'
bspc config presel_feedback_color '#512da8'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
setxkbmap -layout us,es -variant , -option grp:alt_shift_toggle
feh --bg-fill ~/Wallpapers/archkali.png &
~/.config/polybar/./launch.sh --shapes &
picom --config ~/.config/picom/picom.conf &
